Repository OCA/data-protection, pull requests merged in 2019-03, with the labels that each got.

#25 [10.0][UPD] privacy_consent: set partner lang on mail template
  privacy_consent/data/mail.xml
Labels: approved

#26 [FIX] privacy_consent: Avoid race condition with mail queue cron
  privacy_consent/__init__.py
  privacy_consent/models/mail_mail.py
  privacy_consent/models/privacy_activity.py
  privacy_consent/models/privacy_consent.py
  privacy_consent/wizards/__init__.py
  privacy_consent/wizards/mail_compose_message.py
Labels: approved, bug

#19 [11.0][MIG] privacy_partner_report
  privacy_partner_report/README.rst
  privacy_partner_report/__init__.py
  privacy_partner_report/__manifest__.py
  privacy_partner_report/i18n/privacy_partner_report.pot
  privacy_partner_report/readme/CONTRIBUTORS.rst
  privacy_partner_report/readme/DESCRIPTION.rst
  privacy_partner_report/readme/USAGE.rst
  privacy_partner_report/report/__init__.py
  privacy_partner_report/report/privacy_partner_xlsx.py
  privacy_partner_report/static/description/icon.png
  privacy_partner_report/static/description/index.html
  privacy_partner_report/views/privacy_menu_view.xml
  privacy_partner_report/views/privacy_report.xml
  privacy_partner_report/wizard/__init__.py
  privacy_partner_report/wizard/privacy_report_partner.py
  privacy_partner_report/wizard/privacy_report_partner_wizard.xml
Labels: approved, needs review
